- hosts: localhost
  connection: local
  remote_user: ansusr
  become: yes
  gather_facts: no
  vars_files:
          - awscrd.yml
  tasks:
      - name: create a couple of IAM users
        iam:
              aws_access_key: "{{ aws_id }}"
              aws_secret_key: "{{ aws_key }}"
              region: "{{ aws_region }}"
              iam_type: user
              name: "{{ item }}"
              state: present
              password: "Login@123"
              access_key_state: create
        with_items:
            - puppetusr
            - gitusr 
