--- #creating a VPC
- hosts: localhost
  connection: local
  remote_user: ansusr1 
  become: yes
  gather_facts: no
  vars_files:
            - awscrd.yml
  tasks: 
      - name: Create myvpc1
        ec2_vpc_net:
               aws_access_key: "{{ aws_id }}"
               aws_secret_key: "{{ aws_key }}"
               region: "{{ aws_region }}"
               name: myvpcl
               state: present
               cidr_block: 20.0.0.0/16
        register: vpcnet
      - debug: var=vpcnet
