---
- hosts: localhost
  connection: local
  remote_user: kranthik918 
  become: yes
  gather_facts: no
  vars_files: 
         - awscrd.yml 
  tasks: 
       - name: installing ec2 instance
         ec2:
             instance_type: t2.micro
             aws_access_key: "{{aws_id}}"
             aws_secret_key: "{{aws_key}}"
             region: "{{aws_region}}"
             image: ami-f2d3638a 
             count: 1
             vpc_subnet_id: subnet-83f7f1cb
             group_id: sg-7cb15c03 
             assign_public_ip: yes
             key_name: kranthi999 
