---
- hosts: 54.187.112.150
  remote_user: ec2-user 
  become: yes
  tasks:
        - name: install httpd server
          yum: name=httpd state=present
        - name: copy index.html
          copy: src=index.html dest=/var/www/html/index.html
        - name: restart service
          service: name=httpd state=restarted
